### ISSUE TITLE
Add cluster tag from CLUSTER_NAME env

### ISSUE THREAD

**Issue by maximmi** [wichert/k8s-sentry#3]
@wichert I would like to ask you to add this feature in same way it was done [here](https://github.com/getsentry/sentry-kubernetes/pull/24).
Going to use yours instead due to memory leak issue.
Thanks you in advance!

**Comment by wichert** [comment]
If you name your clusters that already happens, since I copy the cluster name from the event to a tag already:

```go
	if evt.ClusterName != "" {
		sentryEvent.Tags["cluster"] = evt.ClusterName
	}
```

Doesn't that work for you?

**Comment by wichert** [comment]
I'm going to close this for now.
